server:
  port: 8007

spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: tap-spring-hibernate-addresses
  jackson:
    default-property-inclusion: NON_NULL

mongock:
  enabled: true
  migration-scan-package:
    - com.infinitelambda.userservice.migrations