server:
  port: 8004
spring:
  data:
    mongodb:
      host: localhost
      port: 49393
      database: tap-spring-hibernate-users
  jackson:
    default-property-inclusion: NON_NULL

mongock:
  enabled: true
  migration-scan-package:
    - com.infinitelambda.userservice.migrations