server:
  port: 8004
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/tap-spring-hibernate-users
  jackson:
    default-property-inclusion: NON_NULL

mongock:
  enabled: true
  migration-scan-package:
    - com.infinitelambda.userservice.migrations
